### ISSUE TITLE
[REPL]

### ISSUE THREAD

**Issue by nagayev** [aNNiMON/Own-Programming-Language-Tutorial#1]
Why syntax 
`
print((1)
` is correct?

**Comment by aNNiMON** [comment]
The problem is not with REPL, but with this: 
https://github.com/aNNiMON/Own-Programming-Language-Tutorial/blob/c6a2f71457d97279cbe91fd3baf9be5e0808bcfb/src/main/java/com/annimon/ownlang/parser/Parser.java#L704-L708
Closing parentheses are optional now. `println (((((((((((((((((((((1` is also valid :laughing:

I think, it's time to add strict check for that. Thanks for pointing me out on this issue.

**Comment by nagayev** [comment]
@aNNiMON okey, it's cool
